# Generated by Django 5.2.3 on 2025-10-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'categories', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='',
        ),
    ]
