# Generated by Django 5.2.3 on 2025-10-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
