# Generated by Django 5.2.3 on 2025-10-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
